use std::fs;
use std::path::Path;

const WELL_KNOWN_TYPE: &str = "WELL_KNOWN_SID_TYPE";

fn main() {
    let mut args = std::env::args();
    let _program = args.next();

    match (args.next().as_deref(), args.next()) {
        (Some("regenerate-bindings"), None) => regenerate_bindings(),
        (Some("-h" | "--help"), None) => print_help(),
        (None, None) => {
            print_help();
            std::process::exit(2);
        }
        _ => {
            eprintln!("error: unknown xtask command or unexpected arguments");
            print_help();
            std::process::exit(2);
        }
    }
}

fn print_help() {
    eprintln!(
        "Repository maintenance tasks

Usage:
    cargo xtask <command>

Commands:
    regenerate-bindings    Regenerate the vendored Windows bindings and well-known SID constants"
    );
}

fn regenerate_bindings() {
    let root = Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("xtask must remain directly under the repository root");
    let output_dir = root.join("target").join("regenerate-bindings");
    fs::create_dir_all(&output_dir).expect("failed to create generator output directory");

    generate_bindings(root, &output_dir);
    generate_well_known(root, &output_dir);
}

fn generate_bindings(root: &Path, output_dir: &Path) {
    let generated = output_dir.join("bindings.rs");
    windows_bindgen::bindgen([
        "--out",
        path_str(&generated),
        "--flat",
        "--sys",
        "--no-deps",
        "--no-allow",
        "--filter",
        "CreateWellKnownSid",
        "ConvertStringSidToSidA",
        "EqualDomainSid",
        "GetLastError",
        "GetWindowsAccountDomainSid",
        "IsWellKnownSid",
        "LocalFree",
        "ERROR_INSUFFICIENT_BUFFER",
    ])
    .unwrap();

    fs::copy(generated, root.join("src").join("bindings.rs"))
        .expect("failed to vendor private Windows bindings");
}

fn generate_well_known(root: &Path, output_dir: &Path) {
    let generated = output_dir.join("well_known.rs");
    windows_bindgen::bindgen([
        "--out",
        path_str(&generated),
        "--flat",
        "--sys",
        "--no-deps",
        "--no-allow",
        "--filter",
        WELL_KNOWN_TYPE,
        "Windows.Win32.Security.Win*",
    ])
    .unwrap();

    let raw = fs::read_to_string(generated).expect("failed to read generated constants");
    let mut wrapped = String::from(
        "// Bindings generated by `windows-bindgen`\n\
         // Regenerate with `cargo xtask regenerate-bindings`.\n\
         \n\
         use crate::WellKnownSidType;\n\
         \n",
    );

    for line in raw.lines() {
        if line.is_empty()
            || line.starts_with("// Bindings generated by ")
            || line == format!("pub type {WELL_KNOWN_TYPE} = i32;")
        {
            continue;
        }

        let declaration = line
            .strip_prefix("pub const ")
            .expect("unexpected item in generated well-known SID bindings");
        let (name, value) = declaration
            .split_once(&format!(": {WELL_KNOWN_TYPE} = "))
            .expect("unexpected well-known SID constant declaration");
        let value = value
            .strip_suffix("i32;")
            .expect("unexpected well-known SID constant value");
        wrapped.push_str(&format!(
            "pub const {name}: WellKnownSidType = WellKnownSidType({value});\n"
        ));
    }

    fs::write(root.join("src").join("well_known.rs"), wrapped)
        .expect("failed to vendor wrapped well-known SID constants");
}

fn path_str(path: &Path) -> &str {
    path.to_str().expect("repository path must be valid UTF-8")
}
