// Bindings generated by `windows-bindgen` 0.63.0

windows_link::link!("advapi32.dll" "system" fn ConvertStringSidToSidA(stringsid : PCSTR, sid : *mut PSID) -> BOOL);
windows_link::link!("advapi32.dll" "system" fn CreateWellKnownSid(wellknownsidtype : WELL_KNOWN_SID_TYPE, domainsid : PSID, psid : PSID, cbsid : *mut u32) -> BOOL);
windows_link::link!("advapi32.dll" "system" fn EqualDomainSid(psid1 : PSID, psid2 : PSID, pfequal : *mut BOOL) -> BOOL);
windows_link::link!("kernel32.dll" "system" fn GetLastError() -> WIN32_ERROR);
windows_link::link!("advapi32.dll" "system" fn GetWindowsAccountDomainSid(psid : PSID, pdomainsid : PSID, cbdomainsid : *mut u32) -> BOOL);
windows_link::link!("advapi32.dll" "system" fn IsWellKnownSid(psid : PSID, wellknownsidtype : WELL_KNOWN_SID_TYPE) -> BOOL);
windows_link::link!("kernel32.dll" "system" fn LocalFree(hmem : HLOCAL) -> HLOCAL);
pub type BOOL = i32;
pub const ERROR_INSUFFICIENT_BUFFER: WIN32_ERROR = 122u32;
pub type HLOCAL = *mut core::ffi::c_void;
pub type PCSTR = *const u8;
pub type PSID = *mut core::ffi::c_void;
pub type WELL_KNOWN_SID_TYPE = i32;
pub type WIN32_ERROR = u32;
